ci:
  skip: []

exclude: '^.*\.(patch)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        types: []
        args: ["-o", "all", "-e", "2148", "-e", "SC2033", "-e", "SC2032", "-e", "SC2034", "-e", "SC2154", "-e", "SC2312", "-e", "SC2164", "-e", "SC2143", "-e", "SC2103"]
        files: '^.*\.(pacscript|sh)$'
  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v3.7.0.1
    hooks:
      - id: shfmt
        args: ["-i", "2", "-bn", "-ci", "-sr", "-s"]
        types: []
        exclude: |
          (?x)^(
            packages/emacs/emacs.pacscript|
            packages/emacs-git/emacs-git.pacscript|
          )$
        files: '^.*\.(pacscript|sh)$'
  - repo: local
    hooks:
      - id: check-packagelist
        name: verify packagelist file is up to date
        language: script
        entry: .check-packagelist.sh
# vim:set ft=yaml ts=2 sw=2 et:
